// Generated by scripts/pack-eyes.ts; do not edit.
/**
 * URLs of the humanoid-kit-eyes pack files. Pass to `loadEyeLibrary`.
 * Every file is a literal `new URL(..., import.meta.url)` so bundlers emit it automatically.
 */
export const eyesPack = {
	manifest: new URL("./data/manifest.json", import.meta.url).href,
	files: {
		"bobby_03_daz_dragon_eyes.webp": new URL("./data/bobby_03_daz_dragon_eyes.webp", import.meta.url).href,
		"bobby_03_diffuse_amber_eyes.webp": new URL("./data/bobby_03_diffuse_amber_eyes.webp", import.meta.url).href,
		"bobby_03_diffuse_blue_eyes.webp": new URL("./data/bobby_03_diffuse_blue_eyes.webp", import.meta.url).href,
		"bobby_03_diffuse_grey_eyes.webp": new URL("./data/bobby_03_diffuse_grey_eyes.webp", import.meta.url).href,
		"bobby_03_diffuse_hazel_eyes.webp": new URL("./data/bobby_03_diffuse_hazel_eyes.webp", import.meta.url).href,
		"bobby_03_diffuse_sea_breeze_eyes.webp": new URL("./data/bobby_03_diffuse_sea_breeze_eyes.webp", import.meta.url).href,
		"culturalibre_6_eyes.webp": new URL("./data/culturalibre_6_eyes.webp", import.meta.url).href,
		"culturalibre_hero_white_eyes.webp": new URL("./data/culturalibre_hero_white_eyes.webp", import.meta.url).href,
		"culturalibre_hero_yellow_eyes.webp": new URL("./data/culturalibre_hero_yellow_eyes.webp", import.meta.url).href,
		"culturalibre_zombie_eyes.webp": new URL("./data/culturalibre_zombie_eyes.webp", import.meta.url).href,
		"gpedroso_blank_eye.webp": new URL("./data/gpedroso_blank_eye.webp", import.meta.url).href,
		"hatshj_alien_eye_2.webp": new URL("./data/hatshj_alien_eye_2.webp", import.meta.url).href,
		"hatshj_alien_eyes.webp": new URL("./data/hatshj_alien_eyes.webp", import.meta.url).href,
		"hatshj_cross_eye.webp": new URL("./data/hatshj_cross_eye.webp", import.meta.url).href,
		"hatshj_facette_eye.webp": new URL("./data/hatshj_facette_eye.webp", import.meta.url).href,
		"hatshj_facette_eye_2.webp": new URL("./data/hatshj_facette_eye_2.webp", import.meta.url).href,
		"hatshj_reptile_eyes.webp": new URL("./data/hatshj_reptile_eyes.webp", import.meta.url).href,
		"mindfront_brown_eye_02.webp": new URL("./data/mindfront_brown_eye_02.webp", import.meta.url).href,
		"nyloseth_bluecateyes.webp": new URL("./data/nyloseth_bluecateyes.webp", import.meta.url).href,
		"nyloseth_brown_cat_eyes.webp": new URL("./data/nyloseth_brown_cat_eyes.webp", import.meta.url).href,
		"nyloseth_green_cat_eyes.webp": new URL("./data/nyloseth_green_cat_eyes.webp", import.meta.url).href,
		"nyloseth_sapphire_blue_eyes.webp": new URL("./data/nyloseth_sapphire_blue_eyes.webp", import.meta.url).href,
		"nyloseth_sapphire_cat_eyes.webp": new URL("./data/nyloseth_sapphire_cat_eyes.webp", import.meta.url).href,
		"nyloseth_yellow_cat_eyes.webp": new URL("./data/nyloseth_yellow_cat_eyes.webp", import.meta.url).href,
		"sonntag78_orcifyhead_eye.webp": new URL("./data/sonntag78_orcifyhead_eye.webp", import.meta.url).href,
		"spamrakuen_sr_anime_eyes_navy.webp": new URL("./data/spamrakuen_sr_anime_eyes_navy.webp", import.meta.url).href,
		"spamrakuen_sr_anime_maid-san_blue_eyes.webp": new URL("./data/spamrakuen_sr_anime_maid-san_blue_eyes.webp", import.meta.url).href,
		"spamrakuen_sr_anime_maid-san_red_eyes.webp": new URL("./data/spamrakuen_sr_anime_maid-san_red_eyes.webp", import.meta.url).href,
		"titleknown_trans_eyes.webp": new URL("./data/titleknown_trans_eyes.webp", import.meta.url).href,
		"wojackowl_blue_eyes_toon.webp": new URL("./data/wojackowl_blue_eyes_toon.webp", import.meta.url).href,
		"wojackowl_brown_eyes_toon.webp": new URL("./data/wojackowl_brown_eyes_toon.webp", import.meta.url).href,
		"wojackowl_green_eyes_toon.webp": new URL("./data/wojackowl_green_eyes_toon.webp", import.meta.url).href,
	},
};
