import { describe, expect, it } from "vitest";
import { AUTHORING_FIGURE, MOUND, moundTargets } from "../scripts/lib/detail/mound.ts";
import { HumanoidModel } from "../src/model/humanoidModel.ts";
import { loadFixtureAssets } from "./fixtures.ts";

/**
 * The mound (mons pubis) as authored detail: a bell of displacement along the
 * skin's outward normal, sized from the measured dimensions
 * (docs/research/ADULT-ANATOMY-DATA.md, section E), generated by code on the
 * adult surface's lattice. These tests hold the form to its numbers and to its
 * symmetry, so an edit to the generator cannot silently change the figure.
 */
const model = new HumanoidModel(loadFixtureAssets(true), { subdivision: 1 });
const lattice = model.adultDetailLattice(AUTHORING_FIGURE);
if (!lattice) throw new Error("no adult surface");
const { fuller, flatter } = moundTargets(lattice);

const at = (v: number) => [0, 1, 2].map((k) => lattice.positions[v * 3 + k] as number);
const nrm = (v: number) => [0, 1, 2].map((k) => lattice.normals[v * 3 + k] as number);
const size = (xyz: Float32Array, i: number) =>
  Math.hypot(xyz[i * 3] as number, xyz[i * 3 + 1] as number, xyz[i * 3 + 2] as number);

describe("the mound's detail targets", { timeout: 120_000 }, () => {
  it("names real lattice vertices, once each, in order", () => {
    for (const t of [fuller, flatter]) {
      expect(t.indices.length).toBeGreaterThan(100);
      expect(t.xyz.length).toBe(t.indices.length * 3);
      for (let i = 0; i < t.indices.length; i++) {
        expect(t.indices[i] as number).toBeLessThan(lattice.vertexCount);
        if (i > 0) expect(t.indices[i] as number).toBeGreaterThan(t.indices[i - 1] as number);
      }
      expect(t.xyz.every(Number.isFinite)).toBe(true);
    }
  });

  it("peaks at its stated height, fuller outward and flatter inward, along the skin's normal", () => {
    let peakFuller = 0;
    let peakFlatter = 0;
    fuller.indices.forEach((v, i) => {
      const s = size(fuller.xyz, i);
      peakFuller = Math.max(peakFuller, s);
      // Along the outward normal exactly.
      const n = nrm(v);
      const dot = [0, 1, 2].reduce(
        (sum, k) => sum + (fuller.xyz[i * 3 + k] as number) * (n[k] as number),
        0,
      );
      expect(dot).toBeCloseTo(s, 7);
    });
    flatter.indices.forEach((v, i) => {
      const s = size(flatter.xyz, i);
      peakFlatter = Math.max(peakFlatter, s);
      const n = nrm(v);
      const dot = [0, 1, 2].reduce(
        (sum, k) => sum + (flatter.xyz[i * 3 + k] as number) * (n[k] as number),
        0,
      );
      expect(dot).toBeCloseTo(-s, 7);
    });
    // A vertex lies within a lattice cell (2.3 mm) of the centre, where the bell is within 1% of its top.
    expect(peakFuller).toBeGreaterThan(MOUND.fuller * 0.98);
    expect(peakFuller).toBeLessThanOrEqual(MOUND.fuller + 1e-9);
    expect(peakFlatter).toBeGreaterThan(MOUND.flatter * 0.98);
    expect(peakFlatter).toBeLessThanOrEqual(MOUND.flatter + 1e-9);
  });

  it("stays inside an ellipse of the measured width and length, and fades to nothing at its edge", () => {
    const ys = fuller.indices.map((v) => at(v)[1] as number);
    const xs = fuller.indices.map((v) => Math.abs(at(v)[0] as number));
    expect(Math.max(...xs)).toBeLessThanOrEqual(MOUND.width / 2 + 1e-9);
    const height = Math.max(...ys) - Math.min(...ys);
    expect(height).toBeLessThanOrEqual(MOUND.length + 1e-9);
    // Within 2 cm of the edge the displacement is a small fraction of the peak.
    const rim = fuller.indices.filter((_, i) => {
      const v = fuller.indices[i] as number;
      const [x, y] = at(v) as [number, number, number];
      void y;
      return Math.abs(x) > MOUND.width / 2 - 0.004;
    });
    for (const v of rim) {
      const i = fuller.indices.indexOf(v);
      expect(size(fuller.xyz, i)).toBeLessThan(MOUND.fuller * 0.1);
    }
  });

  it("is symmetric about the midline", () => {
    // A displaced vertex's mirror image across x = 0 is displaced by the same amount.
    const byKey = new Map<string, number>();
    const key = (x: number, y: number, z: number) =>
      [x, y, z].map((c) => Math.round(c * 2000)).join(",");
    fuller.indices.forEach((v, i) => {
      const [x, y, z] = at(v) as [number, number, number];
      byKey.set(key(x, y, z), size(fuller.xyz, i));
    });
    let checked = 0;
    fuller.indices.forEach((v, i) => {
      const [x, y, z] = at(v) as [number, number, number];
      if (Math.abs(x) < 0.002) return;
      const mirror = byKey.get(key(-x, y, z));
      if (mirror === undefined) return;
      checked++;
      expect(mirror).toBeCloseTo(size(fuller.xyz, i), 4);
    });
    expect(checked).toBeGreaterThan(100);
  });

  it("is the same twice, and fuller and flatter move the same vertices", () => {
    const again = moundTargets(lattice).fuller;
    expect(Array.from(again.indices)).toEqual(Array.from(fuller.indices));
    expect(Array.from(again.xyz)).toEqual(Array.from(fuller.xyz));
    expect(Array.from(flatter.indices)).toEqual(Array.from(fuller.indices));
  });

  it("does not reach the buttocks or the inner thighs, which face away from the front", () => {
    for (const v of fuller.indices) {
      expect(nrm(v)[2] as number).toBeGreaterThan(0.15);
      expect(at(v)[2] as number).toBeGreaterThan(0.05);
    }
  });
});

describe("the mound's weighting, on a lattice built to test it", () => {
  // Five vertices in the mound's window: the front of the pelvis (to place the form), a
  // vertex at its centre facing forward, one at the centre facing sideways, one facing
  // away (a buttock behind it), and one in front but low on the body, outside the window.
  const centreY = 0 + MOUND.lift + MOUND.length / 2;
  const synthetic = (nz: number) => ({
    key: "synthetic",
    vertexCount: 3,
    regionCount: 3,
    positions: Float32Array.from([0, 0, 0.1, 0, centreY, 0.1, 0, centreY, 0.1]),
    normals: Float32Array.from([0, 0, 1, 0, 0, nz, 0, 0, 1]),
  });

  it("drops a vertex whose skin faces away, fades one at a slant and keeps one facing front", () => {
    // Unit normals with a given z; the first vertex fixes the lowest front point at y = 0.
    const lat = (nz: number) => {
      const l = synthetic(nz);
      const s = Math.sqrt(1 - nz * nz);
      l.normals = Float32Array.from([0, 0, 1, s, 0, nz, 0, 0, 1]);
      return l;
    };
    const away = moundTargets(lat(-0.5)).fuller.indices;
    const slant = moundTargets(lat(0.4)).fuller.indices;
    const front = moundTargets(lat(1)).fuller.indices;
    expect(away).not.toContain(1);
    expect(slant).toContain(1);
    expect(front).toContain(1);
    const peak = (nz: number) => {
      const t = moundTargets(lat(nz)).fuller;
      const i = t.indices.indexOf(1);
      return i < 0 ? 0 : size(t.xyz, i);
    };
    expect(peak(0.4)).toBeLessThan(peak(1));
    expect(peak(1)).toBeCloseTo(MOUND.fuller, 4);
  });

  it("refuses a lattice with no front surface on the midline, rather than guessing a place", () => {
    const l = synthetic(1);
    l.normals = Float32Array.from([0, 0, -1, 0, 0, -1, 0, 0, -1]);
    expect(() => moundTargets(l)).toThrow(/no front surface/);
  });
});
