import { describe, expect, it } from "vitest";
import {
  AUTHORING_FIGURE,
  MOUND,
  type MoundPoints,
  moundTargets,
} from "../scripts/lib/control/mound.ts";
import { HumanoidModel } from "../src/model/humanoidModel.ts";
import { createRecipe } from "../src/recipe/recipe.ts";
import { loadFixtureAssets } from "./fixtures.ts";

/**
 * The mound (mons pubis) as authored control targets: a broad, low pad of the
 * measured size with soft margins, generated by code on the base mesh's vertices
 * (docs/research/ADULT-ANATOMY-DATA.md, section E). These tests hold the form to
 * its numbers and its symmetry, and the surface it makes to having no crease, so
 * an edit to the generator cannot silently change the figure.
 */
const model = new HumanoidModel(loadFixtureAssets(true), { subdivision: 1 });
const shape = model.controlShape(AUTHORING_FIGURE);
const count = shape.control.length / 3;
const eligible = new Uint8Array(count);
for (const v of shape.body) eligible[v] = 1;
const points: MoundPoints = { count, positions: shape.control, normals: shape.normals, eligible };
const { fuller, flatter } = moundTargets(points);

const at = (v: number) =>
  [0, 1, 2].map((k) => shape.control[v * 3 + k] as number) as [number, number, number];
const size = (xyz: Float32Array, i: number) =>
  Math.hypot(xyz[i * 3] as number, xyz[i * 3 + 1] as number, xyz[i * 3 + 2] as number);

describe("the mound's control targets", { timeout: 300_000 }, () => {
  it("names real body vertices, once each, in order", () => {
    for (const t of [fuller, flatter]) {
      expect(t.indices.length).toBeGreaterThan(20);
      expect(t.xyz.length).toBe(t.indices.length * 3);
      for (let i = 0; i < t.indices.length; i++) {
        expect(eligible[t.indices[i] as number]).toBe(1);
        if (i > 0) expect(t.indices[i] as number).toBeGreaterThan(t.indices[i - 1] as number);
      }
      expect(t.xyz.every(Number.isFinite)).toBe(true);
    }
    expect(Array.from(flatter.indices)).toEqual(Array.from(fuller.indices));
  });

  it("peaks at exactly its stated height, fuller forward and flatter back", () => {
    let top = 0;
    let topFlatter = 0;
    fuller.indices.forEach((_, i) => {
      top = Math.max(top, size(fuller.xyz, i));
      expect(fuller.xyz[i * 3 + 2] as number).toBeGreaterThan(0);
    });
    flatter.indices.forEach((_, i) => {
      topFlatter = Math.max(topFlatter, size(flatter.xyz, i));
      expect(flatter.xyz[i * 3 + 2] as number).toBeLessThan(0);
    });
    expect(top).toBeCloseTo(MOUND.fuller, 7);
    expect(topFlatter).toBeCloseTo(MOUND.flatter, 7);
  });

  it("leans to the body's forward axis, so it never pushes tissue down into the fold", () => {
    fuller.indices.forEach((_, i) => {
      const s = size(fuller.xyz, i);
      if (s < 1e-6) return;
      // Within 60 degrees of straight forward, and never downward by more than it goes forward.
      expect((fuller.xyz[i * 3 + 2] as number) / s).toBeGreaterThan(0.5);
      expect(fuller.xyz[i * 3 + 1] as number).toBeGreaterThan(-(fuller.xyz[i * 3 + 2] as number));
    });
  });

  it("is a pad of the measured size: broad, soft at its margins, and inside its reach", () => {
    const xs = fuller.indices.map((v) => Math.abs(at(v)[0]));
    expect(Math.max(...xs)).toBeLessThanOrEqual((MOUND.reach * MOUND.width) / 2 + 1e-9);
    // Half its height or more across the measured width (at the middle row).
    const row = fuller.indices
      .map((v, i) => ({ v, s: size(fuller.xyz, i) }))
      .filter(({ v }) => Math.abs(at(v)[0]) < (MOUND.width / 2) * 0.99);
    expect(row.some(({ s }) => s > MOUND.fuller * 0.5)).toBe(true);
    // Soft margins: where the profile reaches its edge it is a small share of the peak.
    fuller.indices.forEach((v, i) => {
      const x = Math.abs(at(v)[0]) / ((MOUND.reach * MOUND.width) / 2);
      if (x > 0.85) expect(size(fuller.xyz, i)).toBeLessThan(MOUND.fuller * 0.2);
    });
  });

  it("is symmetric about the midline", () => {
    const byKey = new Map<string, number>();
    const key = (x: number, y: number, z: number) =>
      [x, y, z].map((c) => Math.round(c * 2000)).join(",");
    fuller.indices.forEach((v, i) => {
      const [x, y, z] = at(v);
      byKey.set(key(x, y, z), size(fuller.xyz, i));
    });
    let checked = 0;
    fuller.indices.forEach((v, i) => {
      const [x, y, z] = at(v);
      if (Math.abs(x) < 0.002) return;
      const mirror = byKey.get(key(-x, y, z));
      if (mirror === undefined) return;
      checked++;
      expect(mirror).toBeCloseTo(size(fuller.xyz, i), 4);
    });
    expect(checked).toBeGreaterThan(10);
  });

  it("is the same twice", () => {
    const again = moundTargets(points).fuller;
    expect(Array.from(again.indices)).toEqual(Array.from(fuller.indices));
    expect(Array.from(again.xyz)).toEqual(Array.from(fuller.xyz));
  });

  it("moves no vertex the drawn body does not use", () => {
    // Hand a mask that excludes the middle of the pad: nothing there may move.
    const mask = Uint8Array.from(eligible);
    const first = fuller.indices[Math.floor(fuller.indices.length / 2)] as number;
    mask[first] = 0;
    const moved = moundTargets({ ...points, eligible: mask }).fuller.indices;
    expect(moved).not.toContain(first);
  });
});

describe("the mound's weighting, on points built to test it", () => {
  // A column of vertices up the midline of a pelvis that faces forward above a fold: the fold at
  // y = 0, the surface turning under below it, a vertex facing away behind, one far off to the side.
  const build = (ys: number[], nz: number[]): MoundPoints => ({
    count: ys.length,
    positions: Float32Array.from(ys.flatMap((y) => [0, y, 0.1])),
    normals: Float32Array.from(nz.flatMap((z) => [0, Math.sqrt(1 - z * z), z])),
  });

  it("rises smoothly from nothing at the fold to its full height, and never turns back down", () => {
    const ys = Array.from({ length: 41 }, (_, i) => i * 0.003);
    const p = build(
      ys,
      ys.map(() => 1),
    );
    const w = moundTargets(p).fuller;
    const size_ = new Map(w.indices.map((v, i) => [v, size(w.xyz, i)] as const));
    const column = ys.map((_, i) => size_.get(i) ?? 0);
    const peak = column.indexOf(Math.max(...column));
    for (let i = 1; i <= peak; i++)
      expect(column[i]).toBeGreaterThanOrEqual(column[i - 1] as number);
    // Nothing at the fold itself, and no step: neighbouring vertices differ by a fraction of the peak.
    expect(column[0]).toBe(0);
    for (let i = 1; i < column.length; i++)
      expect(Math.abs((column[i] as number) - (column[i - 1] as number))).toBeLessThan(
        MOUND.fuller * 0.35,
      );
  });

  it("gives nothing to skin that faces away, and fades it where it is slanted", () => {
    const ys = [0, 0.04, 0.04, 0.04];
    const p = build(ys, [1, 1, 0.3, -0.5]);
    const w = moundTargets(p).fuller;
    const found = new Map(w.indices.map((v, i) => [v, size(w.xyz, i)] as const));
    expect(found.get(3)).toBeUndefined();
    expect(found.get(2) ?? 0).toBeLessThan(found.get(1) ?? 0);
    expect(found.get(1)).toBeCloseTo(MOUND.fuller, 6);
  });

  it("refuses points with no front surface on the midline, rather than guessing a place", () => {
    expect(() => moundTargets(build([0, 0.01], [-1, -1]))).toThrow(/no front surface/);
  });
});

describe("the surface the mound makes", { timeout: 600_000 }, () => {
  const MOD = "pelvis/mound-decr|incr";
  const edgeShading = (gender: number, value: number) => {
    const surface = model.adultSurface() as NonNullable<ReturnType<typeof model.adultSurface>>;
    const recipe = (v: number) =>
      createRecipe({ macros: { age: 30, gender }, modifiers: v ? { [MOD]: v } : {} });
    const base = model.evaluate(recipe(0));
    const moved = model.evaluate(recipe(value));
    const count = base.positions.length / 3;
    const seen = new Set<number>();
    let worst = 0;
    const angle = (n: Float32Array, i: number, j: number) =>
      (Math.acos(
        Math.max(
          -1,
          Math.min(
            1,
            (n[i * 3] as number) * (n[j * 3] as number) +
              (n[i * 3 + 1] as number) * (n[j * 3 + 1] as number) +
              (n[i * 3 + 2] as number) * (n[j * 3 + 2] as number),
          ),
        ),
      ) *
        180) /
      Math.PI;
    for (let t = 0; t < surface.index.length; t += 3)
      for (let k = 0; k < 3; k++) {
        const i = surface.index[t + k] as number;
        const j = surface.index[t + ((k + 1) % 3)] as number;
        if (i === j) continue;
        const key = Math.min(i, j) * count + Math.max(i, j);
        if (seen.has(key)) continue;
        seen.add(key);
        worst = Math.max(worst, Math.abs(angle(moved.normals, i, j) - angle(base.normals, i, j)));
      }
    return worst;
  };

  it("has no crease: no edge's shading turns by more than a few degrees more than it does without it", () => {
    // The shading normals are what a viewer sees; a ledge or a rim is a jump in them between
    // neighbouring vertices. The pad's own curvature (1.5 cm over 6.5 cm) is a few degrees an edge.
    for (const gender of [0, 0.5, 1]) {
      expect(edgeShading(gender, 1), `fuller, gender ${gender}`).toBeLessThan(7);
      expect(edgeShading(gender, -1), `flatter, gender ${gender}`).toBeLessThan(4);
    }
  });
});
