// Generated by scripts/pack-animations.ts; do not edit.
/** URLs of the humanoid-kit-animations pack files. Pass to `loadAnimationLibrary`. */
export declare const animationsPack: {
	readonly manifest: string;
	readonly files: Readonly<Record<"idle1.bin.gz" | "idle2.bin.gz" | "idlehips.bin.gz" | "swimcrawlstroke.bin.gz" | "walk_female.bin.gz" | "walk_normal.bin.gz", string>>;
};
