// Generated by scripts/pack-animations.ts; do not edit.
/**
 * URLs of the humanoid-kit-animations pack files. Pass to `loadAnimationLibrary`.
 * Every file is a literal `new URL(..., import.meta.url)` so bundlers emit it automatically.
 */
export const animationsPack = {
	manifest: new URL("./data/manifest.json", import.meta.url).href,
	files: {
		"idle1.bin.gz": new URL("./data/idle1.bin.gz", import.meta.url).href,
		"idle2.bin.gz": new URL("./data/idle2.bin.gz", import.meta.url).href,
		"idlehips.bin.gz": new URL("./data/idlehips.bin.gz", import.meta.url).href,
		"swimcrawlstroke.bin.gz": new URL("./data/swimcrawlstroke.bin.gz", import.meta.url).href,
		"walk_female.bin.gz": new URL("./data/walk_female.bin.gz", import.meta.url).href,
		"walk_normal.bin.gz": new URL("./data/walk_normal.bin.gz", import.meta.url).href,
	},
};
