// Generated by scripts/pack-makehuman.ts; do not edit.
/**
 * URLs of the humanoid-kit-clothing pack files. Pass to `loadHumanoidAssets({ clothing })`.
 * Every file is a literal `new URL(..., import.meta.url)` so bundlers emit it automatically.
 */
export const clothingPack = {
	manifest: new URL("./data/manifest.json", import.meta.url).href,
	files: {
		"garments.bin.gz": new URL("./data/garments.bin.gz", import.meta.url).href,
		"hats_fedora01_fedora_diffuse.webp": new URL("./data/hats_fedora01_fedora_diffuse.webp", import.meta.url).href,
		"hats_fedora01_fedora_normal.webp": new URL("./data/hats_fedora01_fedora_normal.webp", import.meta.url).href,
		"shoes_shoes01_shoes01_diffuse.webp": new URL("./data/shoes_shoes01_shoes01_diffuse.webp", import.meta.url).href,
		"shoes_shoes01_shoes01_normal.webp": new URL("./data/shoes_shoes01_shoes01_normal.webp", import.meta.url).href,
		"shoes_shoes02_shoes02_diffuse.webp": new URL("./data/shoes_shoes02_shoes02_diffuse.webp", import.meta.url).href,
		"shoes_shoes03_shoes03_diffuse.webp": new URL("./data/shoes_shoes03_shoes03_diffuse.webp", import.meta.url).href,
		"shoes_shoes04_shoes04_diffuse.webp": new URL("./data/shoes_shoes04_shoes04_diffuse.webp", import.meta.url).href,
		"shoes_shoes04_shoes04_normal.webp": new URL("./data/shoes_shoes04_shoes04_normal.webp", import.meta.url).href,
		"shoes_shoes05_shoes05_diffuse.webp": new URL("./data/shoes_shoes05_shoes05_diffuse.webp", import.meta.url).href,
		"shoes_shoes06_shoes06_diffuse.webp": new URL("./data/shoes_shoes06_shoes06_diffuse.webp", import.meta.url).href,
		"suits_female_casualsuit01_female_casualsuit01_diffuse.webp": new URL("./data/suits_female_casualsuit01_female_casualsuit01_diffuse.webp", import.meta.url).href,
		"suits_female_casualsuit01_female_casualsuit01_normal.webp": new URL("./data/suits_female_casualsuit01_female_casualsuit01_normal.webp", import.meta.url).href,
		"suits_female_casualsuit02_female_casualsuit02_diffuse.webp": new URL("./data/suits_female_casualsuit02_female_casualsuit02_diffuse.webp", import.meta.url).href,
		"suits_female_casualsuit02_female_casualsuit02_normal.webp": new URL("./data/suits_female_casualsuit02_female_casualsuit02_normal.webp", import.meta.url).href,
		"suits_female_elegantsuit01_female_elegantsuit01_diffuse.webp": new URL("./data/suits_female_elegantsuit01_female_elegantsuit01_diffuse.webp", import.meta.url).href,
		"suits_female_elegantsuit01_female_elegantsuit01_normal.webp": new URL("./data/suits_female_elegantsuit01_female_elegantsuit01_normal.webp", import.meta.url).href,
		"suits_female_sportsuit01_female_sportsuit01_diffuse.webp": new URL("./data/suits_female_sportsuit01_female_sportsuit01_diffuse.webp", import.meta.url).href,
		"suits_female_sportsuit01_female_sportsuit01_normal.webp": new URL("./data/suits_female_sportsuit01_female_sportsuit01_normal.webp", import.meta.url).href,
		"suits_male_casualsuit01_male_casualsuit01_diffuse.webp": new URL("./data/suits_male_casualsuit01_male_casualsuit01_diffuse.webp", import.meta.url).href,
		"suits_male_casualsuit01_male_casualsuit01_normal.webp": new URL("./data/suits_male_casualsuit01_male_casualsuit01_normal.webp", import.meta.url).href,
		"suits_male_casualsuit02_male_casualsuit02_diffuse.webp": new URL("./data/suits_male_casualsuit02_male_casualsuit02_diffuse.webp", import.meta.url).href,
		"suits_male_casualsuit02_male_casualsuit02_normal.webp": new URL("./data/suits_male_casualsuit02_male_casualsuit02_normal.webp", import.meta.url).href,
		"suits_male_casualsuit03_male_casualsuit03_diffuse.webp": new URL("./data/suits_male_casualsuit03_male_casualsuit03_diffuse.webp", import.meta.url).href,
		"suits_male_casualsuit03_male_casualsuit03_normal.webp": new URL("./data/suits_male_casualsuit03_male_casualsuit03_normal.webp", import.meta.url).href,
		"suits_male_casualsuit04_male_casualsuit04_diffuse.webp": new URL("./data/suits_male_casualsuit04_male_casualsuit04_diffuse.webp", import.meta.url).href,
		"suits_male_casualsuit04_male_casualsuit04_normal.webp": new URL("./data/suits_male_casualsuit04_male_casualsuit04_normal.webp", import.meta.url).href,
		"suits_male_casualsuit05_male_casualsuit05_diffuse.webp": new URL("./data/suits_male_casualsuit05_male_casualsuit05_diffuse.webp", import.meta.url).href,
		"suits_male_casualsuit05_male_casualsuit05_normal.webp": new URL("./data/suits_male_casualsuit05_male_casualsuit05_normal.webp", import.meta.url).href,
		"suits_male_casualsuit06_male_casualsuit06_diffuse.webp": new URL("./data/suits_male_casualsuit06_male_casualsuit06_diffuse.webp", import.meta.url).href,
		"suits_male_casualsuit06_male_casualsuit06_normal.webp": new URL("./data/suits_male_casualsuit06_male_casualsuit06_normal.webp", import.meta.url).href,
		"suits_male_elegantsuit01_male_elegantsuit01_diffuse.webp": new URL("./data/suits_male_elegantsuit01_male_elegantsuit01_diffuse.webp", import.meta.url).href,
		"suits_male_worksuit01_male_worksuit01_diffuse.webp": new URL("./data/suits_male_worksuit01_male_worksuit01_diffuse.webp", import.meta.url).href,
		"suits_male_worksuit01_male_worksuit01_normal.webp": new URL("./data/suits_male_worksuit01_male_worksuit01_normal.webp", import.meta.url).href,
	},
};
