/**
 * The colour-driven subsurface scattering model, in TypeScript.
 *
 * Every channel's scatter distance follows from its own albedo, so any colour
 * (skin, fur, scales, fantasy) scatters plausibly with no per-colour tuning:
 *
 * 1. surface albedo → single-scattering albedo (Chiang, Kutz & Burley 2016, Eq. 1);
 * 2. → Burley profile width d = α · ℓ / s(A), with the scattering length ℓ
 *    rising with wavelength and s the diffuse-transmission profile scale
 *    (Christensen & Burley 2015, Eq. 6);
 * 3. d times surface curvature, x = d · κ, → the diffuse response of a sphere
 *    of that curvature lit at N·L, pre-integrated over Burley's profile
 *    (Penner 2011; `preintegratedDiffuse` in ./preintegration.ts). It dims the
 *    lit side and carries light past the terminator, more for red, which
 *    scatters furthest.
 *
 * The renderer samples a table of step 3 (`SCATTER_TABLE`, generated by
 * `scripts/generate-scatter-table.ts`), and `scatterTableDiffuse` samples the
 * same bytes the same way, so the sphere parity test can hold the shader to
 * this model exactly. See docs/research/ALGORITHMIC-APPEARANCE.md §2.
 */
import { SCATTER_TABLE } from "./scatterTable.ts";
import type { Rgb } from "./skinTone.ts";

/** Representative wavelengths 612, 549 and 465 nm, relative to 550 nm. */
export const WAVELENGTH_RATIO: Readonly<Rgb> = [612 / 550, 549 / 550, 465 / 550];

/** The scatter parameters `SkinMaterial` uses for natural skin. */
export const SKIN_SCATTER = {
  /** Scattering mean free path at 550 nm, metres (skin ≈ 1.14 mm, Jensen 2001). */
  mfp: 1.14e-3,
  /** How much further red scatters than blue (spectral slope). */
  slope: 1.4,
  /** Fraction of the pigment that sits above an unpigmented scattering layer. */
  pigmentDepth: 0.75,
} as const;

/** Chiang, Kutz & Burley 2016, Eq. 1: surface albedo → single-scattering albedo. */
export const singleScatterAlbedo = (a: number): number =>
  1 - Math.exp(-5.09406 * a + 2.61188 * a * a - 4.31805 * a * a * a);

/** Christensen & Burley 2015, Eq. 6: the diffuse surface transmission profile scale. */
export const profileScale = (a: number): number => 1.9 - a + 3.5 * (a - 0.8) ** 2;

const clampAlbedo = (c: number) => Math.min(0.999, Math.max(0.001, c));

/**
 * Per-channel Burley profile width d, in metres. With `pigmentDepth` p > 0 the
 * medium scatters as `albedo^(1−p) · substrate^p`: pigment above a substrate
 * colours the light without changing how far the substrate carries it.
 */
export function scatterDistance(
  albedo: Readonly<Rgb>,
  mfp: number = SKIN_SCATTER.mfp,
  slope: number = SKIN_SCATTER.slope,
  pigmentDepth = 0,
  substrate: Readonly<Rgb> = albedo,
): Rgb {
  return albedo.map((c, k) => {
    const a =
      clampAlbedo(c) ** (1 - pigmentDepth) * clampAlbedo(substrate[k] as number) ** pigmentDepth;
    const ls = mfp * (WAVELENGTH_RATIO[k] as number) ** slope;
    return (singleScatterAlbedo(a) * ls) / profileScale(a);
  }) as Rgb;
}

/** The table's x axis: u = x / (x + knee), so resolution sits at small x and u = 1 is x = ∞. */
export const scatterTableU = (x: number): number => x / (x + SCATTER_TABLE.knee);

let decoded: Float32Array | null = null;

/** The table's values, decoded from half floats: `cosSteps` per row, one row per u. */
export function scatterTableValues(): Float32Array {
  if (decoded) return decoded;
  const bytes = Uint8Array.from(atob(SCATTER_TABLE.data), (ch) => ch.charCodeAt(0));
  const halves = new Uint16Array(bytes.buffer);
  decoded = Float32Array.from(halves, halfToFloat);
  return decoded;
}

/** IEEE 754 binary16 → number. */
export function halfToFloat(h: number): number {
  const sign = h & 0x8000 ? -1 : 1;
  const exp = (h >> 10) & 0x1f;
  const frac = h & 0x3ff;
  if (exp === 0) return sign * 2 ** -14 * (frac / 1024);
  if (exp === 31) return frac ? Number.NaN : sign * Number.POSITIVE_INFINITY;
  return sign * 2 ** (exp - 15) * (1 + frac / 1024);
}

/**
 * The table's diffuse response, sampled as the GPU samples it: bilinear
 * between texel centres, clamped at the edges, with the exact Lambert term
 * added back (the table holds `preintegratedDiffuse − max(N·L, 0)`).
 */
export function scatterTableDiffuse(nDotL: number, x: number): number {
  const { cosSteps, uSteps } = SCATTER_TABLE;
  const values = scatterTableValues();
  const tx = Math.min(
    cosSteps - 1,
    Math.max(0, ((Math.min(1, Math.max(-1, nDotL)) + 1) / 2) * (cosSteps - 1)),
  );
  const ty = Math.min(uSteps - 1, Math.max(0, scatterTableU(Math.max(0, x)) * (uSteps - 1)));
  const x0 = Math.floor(tx);
  const y0 = Math.floor(ty);
  const x1 = Math.min(cosSteps - 1, x0 + 1);
  const y1 = Math.min(uSteps - 1, y0 + 1);
  const fx = tx - x0;
  const fy = ty - y0;
  const at = (i: number, j: number) => values[j * cosSteps + i] as number;
  const residual =
    (at(x0, y0) * (1 - fx) + at(x1, y0) * fx) * (1 - fy) +
    (at(x0, y1) * (1 - fx) + at(x1, y1) * fx) * fy;
  return Math.max(nDotL, 0) + residual;
}
