// Generated by scripts/pack-makehuman.ts; do not edit.
/** URLs of the humanoid-kit-hair pack files. Pass to `loadHumanoidAssets({ hair })`. */
export declare const hairPack: {
	readonly manifest: string;
	readonly files: Readonly<Record<"afro01.bin.gz" | "afro01.webp" | "bob01.bin.gz" | "bob01.webp" | "bob02.bin.gz" | "bob02.webp" | "braid01.bin.gz" | "braid01.webp" | "long01.bin.gz" | "long01.webp" | "ponytail01.bin.gz" | "ponytail01.webp" | "short01.bin.gz" | "short01.webp" | "short02.bin.gz" | "short02.webp" | "short03.bin.gz" | "short03.webp" | "short04.bin.gz" | "short04.webp", string>>;
};
