// Generated by scripts/pack-makehuman.ts; do not edit.
/**
 * URLs of the humanoid-kit-hair pack files. Pass to `loadHumanoidAssets({ hair })`.
 * Every file is a literal `new URL(..., import.meta.url)` so bundlers emit it automatically.
 */
export const hairPack = {
	manifest: new URL("./data/manifest.json", import.meta.url).href,
	files: {
		"afro01.bin.gz": new URL("./data/afro01.bin.gz", import.meta.url).href,
		"afro01.webp": new URL("./data/afro01.webp", import.meta.url).href,
		"bob01.bin.gz": new URL("./data/bob01.bin.gz", import.meta.url).href,
		"bob01.webp": new URL("./data/bob01.webp", import.meta.url).href,
		"bob02.bin.gz": new URL("./data/bob02.bin.gz", import.meta.url).href,
		"bob02.webp": new URL("./data/bob02.webp", import.meta.url).href,
		"braid01.bin.gz": new URL("./data/braid01.bin.gz", import.meta.url).href,
		"braid01.webp": new URL("./data/braid01.webp", import.meta.url).href,
		"long01.bin.gz": new URL("./data/long01.bin.gz", import.meta.url).href,
		"long01.webp": new URL("./data/long01.webp", import.meta.url).href,
		"ponytail01.bin.gz": new URL("./data/ponytail01.bin.gz", import.meta.url).href,
		"ponytail01.webp": new URL("./data/ponytail01.webp", import.meta.url).href,
		"short01.bin.gz": new URL("./data/short01.bin.gz", import.meta.url).href,
		"short01.webp": new URL("./data/short01.webp", import.meta.url).href,
		"short02.bin.gz": new URL("./data/short02.bin.gz", import.meta.url).href,
		"short02.webp": new URL("./data/short02.webp", import.meta.url).href,
		"short03.bin.gz": new URL("./data/short03.bin.gz", import.meta.url).href,
		"short03.webp": new URL("./data/short03.webp", import.meta.url).href,
		"short04.bin.gz": new URL("./data/short04.bin.gz", import.meta.url).href,
		"short04.webp": new URL("./data/short04.webp", import.meta.url).href,
	},
};
