/**
 * The adult pack's own authored shape: targets generated by code rather than read
 * from MakeHuman, the modifiers that drive them and their sliders
 * (docs/research/ADULT-SCULPT-PLAN.md).
 *
 * Today that is the mound, a control target (a swell too broad for the lattice's
 * fine cells to be worth it, see `control/mound.ts`). Features that need finer
 * cells than the base's, and reservoirs to extrude from, are authored as detail
 * on the adult surface's lattice (`anatomy.detail`, `anatomy.reservoirs`) and
 * join here as they are built.
 *
 * These modifiers are the pack's own, not MakeHuman's, so the packer adds them to
 * the ones it reads from upstream; their ids follow MakeHuman's
 * `group/target-lo|hi` form so the recipe, the age policy and the creator treat
 * them like any other adult modifier.
 */
import type {
  AdultDetailSpec,
  AdultReservoirSpec,
  ShapeModifierEntry,
  SliderEntry,
  SliderTask,
} from "../../src/format/assetFormat.ts";
import type { AdultDetailLattice, ControlShape } from "../../src/model/humanoidModel.ts";
import { moundTargets } from "./control/mound.ts";
import { skinOf } from "./detail/contact.ts";
import { PHALLUS_GIRTH, PHALLUS_LENGTH, PHALLUS_SIZE, phallusTargets } from "./detail/phallus.ts";
import { reservoirRoot } from "./detail/root.ts";
import { scrotumTargets, TESTES_SIZE } from "./detail/scrotum.ts";
import type { MaleParts } from "./detail/sculpt.ts";
import { type EncodedTarget, encodeSparseTarget } from "./targetEncoding.ts";

/**
 * The modifiers the pack authors. All are adult-only. The phallic organ's are
 * virtual (an end named "" has no target, `recipeContributions`): they carry a
 * value, and the detail's `drives` read it (`detail/phallus.ts`).
 */
export const AUTHORED_MODIFIERS: readonly ShapeModifierEntry[] = [
  {
    id: "pelvis/mound-decr|incr",
    group: "pelvis",
    lo: "pelvis/mound-decr",
    hi: "pelvis/mound-incr",
    adultOnly: true,
  },
  { id: PHALLUS_SIZE, group: "genitals", lo: null, hi: "", adultOnly: true },
  { id: PHALLUS_LENGTH, group: "genitals", lo: "", hi: "", adultOnly: true },
  { id: PHALLUS_GIRTH, group: "genitals", lo: "", hi: "", adultOnly: true },
  { id: TESTES_SIZE, group: "genitals", lo: null, hi: "", adultOnly: true },
];

/**
 * The slider of each authored modifier, placed after the upstream slider named
 * by `after`, in the order listed.
 */
const AUTHORED_SLIDERS = [
  {
    mod: "pelvis/mound-decr|incr",
    after: "pelvis/bulge-decr|incr",
    label: "Mound",
    description: "The fullness of the mound over the pubic bone, flatter to fuller.",
  },
  {
    mod: PHALLUS_SIZE,
    after: "genitals/penis-length-decr|incr",
    label: "Phallus size",
    description:
      "From none through a clitoral glans to a large penis. Sizes between are blends of shapes made at several sizes, not one shape scaled.",
  },
  {
    mod: PHALLUS_LENGTH,
    after: PHALLUS_SIZE,
    label: "Phallus length",
    description: "Shorter or longer than the size sets, by up to two standard deviations.",
  },
  {
    mod: PHALLUS_GIRTH,
    after: PHALLUS_LENGTH,
    label: "Phallus girth",
    description: "Slimmer or thicker than the size sets, by up to two standard deviations.",
  },
  {
    mod: TESTES_SIZE,
    after: "genitals/penis-testicles-decr|incr",
    label: "Testes size",
    description:
      "From none to a large testis, in one sac of two lobes; the right a little larger than the left, as measured.",
  },
] as const;

/** Upstream sliders the authored ones replace: the CC0 penis targets, whose shape the phallus supersedes. */
export const HIDDEN_SLIDERS: readonly string[] = [
  "genitals/penis-length-decr|incr",
  "genitals/penis-circ-decr|incr",
  "genitals/penis-testicles-decr|incr",
];

/**
 * What the pack authors itself and where each asset comes from, for the pack's
 * PROVENANCE.md: what was referenced, what was authored, and by which script.
 * The genital forms are CC0 community sculpts, projected and sized by code
 * (`packs/adult-anatomy/source/PROVENANCE.md`); nothing else third-party was
 * opened, traced or copied.
 */
export const AUTHORED_PROVENANCE: readonly string[] = [
  "- `pelvis/mound-decr`, `pelvis/mound-incr` (control targets): authored by `scripts/lib/control/mound.ts` " +
    "on the CC0 hm08 base mesh; sized from published soft-tissue measurements (docs/research/ADULT-ANATOMY-DATA.md, section E).",
  "- `genitals/phallus-k2..k4*` (detail targets) and the modifiers `genitals/phallus-size`, `-length-decr|incr`, `-girth-decr|incr`: " +
    "the flaccid shaft, glans and corona of ieroglif's CC0 `adult_male_genitalia_breast_fix` " +
    "(<http://www.makehumancommunity.org/proxy/adult_male_genitalia_breast_fix.html>) and the erect ones of Slayer227's CC0 " +
    "`Male_Gen-Heal1` (<http://www.makehumancommunity.org/proxy/erect_penis_only_works_with_males.html>), " +
    "cut by `scripts/blender/cut_male.py`, placed by `scripts/lib/detail/sculpt.ts` and projected onto the phallic reservoir " +
    "by `scripts/lib/detail/transfer.ts`. `scripts/lib/detail/phallus.ts` grows or shrinks each by one uniform factor to a " +
    "published dorsal length, and blends the flaccid sculpt into the erect one for arousal " +
    "(length, growth and spread: docs/research/ADULT-ANATOMY-DATA.md, section F). `genitals/phallus-k1*` (the clitoral glans) " +
    "is drawn by `scripts/lib/detail/phallus.ts` from the reservoir's loop and published measurements.",
  "- `genitals/testes-k*` (detail targets) and the modifier `genitals/testes-size`: the sac of the same CC0 " +
    "`adult_male_genitalia_breast_fix`, cut, placed and projected onto the labioscrotal reservoir the same way and grown " +
    "or shrunk by `scripts/lib/detail/scrotum.ts` by one uniform factor to the width of two testes of a published volume " +
    "(docs/research/ADULT-ANATOMY-DATA.md, section F); the skin's thickness is modelled and labelled so there.",
];

/** Every target name the pack authors as a control target (a virtual modifier has none). */
export const AUTHORED_TARGET_NAMES: readonly string[] = AUTHORED_MODIFIERS.flatMap((m) =>
  [m.lo, m.hi].filter((t): t is string => !!t),
);

/**
 * The control targets the pack authors, encoded, generated on the authoring
 * figure's control mesh (`HumanoidModel.controlShape`): the mound, on the
 * vertices the drawn body uses.
 */
export function authorControl(shape: ControlShape): EncodedTarget[] {
  const count = shape.control.length / 3;
  const eligible = new Uint8Array(count);
  for (const v of shape.body) eligible[v] = 1;
  const mound = moundTargets({
    count,
    positions: shape.control,
    normals: shape.normals,
    eligible,
  });
  const targets = [
    encodeSparseTarget("pelvis/mound-incr", mound.fuller.indices, mound.fuller.xyz),
    encodeSparseTarget("pelvis/mound-decr", mound.flatter.indices, mound.flatter.xyz),
  ];
  const names = targets.map((t) => t.name).sort();
  const declared = [...AUTHORED_TARGET_NAMES].sort();
  if (names.join() !== declared.join())
    throw new Error(`authored targets ${names} do not match the modifiers' ${declared}`);
  return targets;
}

/**
 * Adds the authored modifiers' sliders to the adult sliders, each after the slider
 * it sits beside, and removes the upstream sliders they replace. The order is the
 * sibling's plus a fraction of a step, so the merged taxonomy keeps upstream's order.
 */
export function addAuthoredSliders(tasks: SliderTask[]): void {
  const authoredIds = new Set<string>(AUTHORED_SLIDERS.map((s) => s.mod));
  for (const s of AUTHORED_SLIDERS) {
    const sibling = tasks
      .flatMap((t) => t.groups)
      .find((g) => g.sliders.some((x) => x.id === s.after));
    const at = sibling?.sliders.findIndex((x) => x.id === s.after) ?? -1;
    if (!sibling || at < 0)
      throw new Error(`authored slider ${s.mod}: no slider ${s.after} to sit by`);
    const next = sibling.sliders[at] as SliderEntry;
    sibling.sliders.splice(at + 1, 0, {
      kind: "modifier",
      id: s.mod,
      label: s.label,
      camera: next.camera,
      description: s.description,
      order: next.order + (authoredIds.has(s.after) ? 0.01 : 0.1),
    });
  }
  for (const group of tasks.flatMap((t) => t.groups))
    group.sliders = group.sliders.filter((x) => !HIDDEN_SLIDERS.includes(x.id));
}

/**
 * The detail targets the pack authors on the adult surface's lattice, encoded,
 * and the spec that names them (`AdultDetailSpec`): the phallic organ on the
 * phallic reservoir. `lattice` is the lattice of a model with the pack's
 * reservoirs, on the authoring figure.
 */
export function authorDetail(
  lattice: AdultDetailLattice,
  reservoirs: readonly AdultReservoirSpec[],
  parts: MaleParts,
): { targets: EncodedTarget[]; detail: AdultDetailSpec } {
  const rootOf = (id: string) => {
    const spec = reservoirs.find((r) => r.id === id);
    if (!spec) throw new Error(`the pack has no reservoir ${id} to draw from`);
    return reservoirRoot(lattice, spec);
  };
  // The skin round the reservoirs, which the organ and the sac rest on.
  const skin = skinOf(
    lattice,
    reservoirs.map((r) => r.cap),
  );
  const organ = phallusTargets(rootOf("phallic"), parts.phallus, skin);
  const sac = scrotumTargets(rootOf("labioscrotal"), parts.scrotum, skin);
  const made = [...organ.targets, ...sac.targets];
  return {
    targets: made.map((t) => encodeSparseTarget(t.name, t.indices, t.xyz)),
    detail: {
      targets: made.map((t) => t.name),
      surfaceKey: lattice.key,
      drives: { ...organ.drives, ...sac.drives },
    },
  };
}
