/**
 * The adult pack's own authored shape: targets generated by code rather than read
 * from MakeHuman, the modifiers that drive them and their sliders
 * (docs/research/ADULT-SCULPT-PLAN.md).
 *
 * Today that is the mound, a control target (a swell too broad for the lattice's
 * fine cells to be worth it, see `control/mound.ts`). Features that need finer
 * cells than the base's, and reservoirs to extrude from, are authored as detail
 * on the adult surface's lattice (`anatomy.detail`, `anatomy.reservoirs`) and
 * join here as they are built.
 *
 * These modifiers are the pack's own, not MakeHuman's, so the packer adds them to
 * the ones it reads from upstream; their ids follow MakeHuman's
 * `group/target-lo|hi` form so the recipe, the age policy and the creator treat
 * them like any other adult modifier.
 */
import type { ShapeModifierEntry, SliderEntry, SliderTask } from "../../src/format/assetFormat.ts";
import type { ControlShape } from "../../src/model/humanoidModel.ts";
import { moundTargets } from "./control/mound.ts";
import { type EncodedTarget, encodeSparseTarget } from "./targetEncoding.ts";

/** The modifiers the pack authors. All are adult-only. */
export const AUTHORED_MODIFIERS: readonly ShapeModifierEntry[] = [
  {
    id: "pelvis/mound-decr|incr",
    group: "pelvis",
    lo: "pelvis/mound-decr",
    hi: "pelvis/mound-incr",
    adultOnly: true,
  },
];

/** The slider of each authored modifier, placed after the upstream slider named by `after`. */
const AUTHORED_SLIDERS = [
  {
    mod: "pelvis/mound-decr|incr",
    after: "pelvis/bulge-decr|incr",
    label: "Mound",
    description: "The fullness of the mound over the pubic bone, flatter to fuller.",
  },
] as const;

/** Every target name the pack authors. */
export const AUTHORED_TARGET_NAMES: readonly string[] = AUTHORED_MODIFIERS.flatMap((m) =>
  m.lo ? [m.lo, m.hi] : [m.hi],
);

/**
 * The control targets the pack authors, encoded, generated on the authoring
 * figure's control mesh (`HumanoidModel.controlShape`): the mound, on the
 * vertices the drawn body uses.
 */
export function authorControl(shape: ControlShape): EncodedTarget[] {
  const count = shape.control.length / 3;
  const eligible = new Uint8Array(count);
  for (const v of shape.body) eligible[v] = 1;
  const mound = moundTargets({
    count,
    positions: shape.control,
    normals: shape.normals,
    eligible,
  });
  const targets = [
    encodeSparseTarget("pelvis/mound-incr", mound.fuller.indices, mound.fuller.xyz),
    encodeSparseTarget("pelvis/mound-decr", mound.flatter.indices, mound.flatter.xyz),
  ];
  const names = targets.map((t) => t.name).sort();
  const declared = [...AUTHORED_TARGET_NAMES].sort();
  if (names.join() !== declared.join())
    throw new Error(`authored targets ${names} do not match the modifiers' ${declared}`);
  return targets;
}

/**
 * Adds the authored modifiers' sliders to the adult sliders, each after the slider
 * it sits beside. The order is the sibling's plus half a step, so the merged
 * taxonomy keeps upstream's order.
 */
export function addAuthoredSliders(tasks: SliderTask[]): void {
  for (const s of AUTHORED_SLIDERS) {
    const sibling = tasks
      .flatMap((t) => t.groups)
      .find((g) => g.sliders.some((x) => x.id === s.after));
    const at = sibling?.sliders.findIndex((x) => x.id === s.after) ?? -1;
    if (!sibling || at < 0)
      throw new Error(`authored slider ${s.mod}: no slider ${s.after} to sit by`);
    const next = sibling.sliders[at] as SliderEntry;
    sibling.sliders.splice(at + 1, 0, {
      kind: "modifier",
      id: s.mod,
      label: s.label,
      camera: next.camera,
      description: s.description,
      order: next.order + 0.5,
    });
  }
}
