/**
 * Writes compiled attachments into a pack directory and generates the pack's
 * `index.js` / `index.d.ts`, which export one literal
 * `new URL("./data/<file>", import.meta.url)` per file so bundlers emit every
 * binary and texture without configuration.
 */
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import type { CompiledAsset } from "./compileAsset.ts";

export interface AttachmentEntry {
  id: string;
  kind: string;
  name: string;
  zDepth: number;
  vertexCount: number;
  faceCount: number;
  scale: CompiledAsset["scale"];
  material: CompiledAsset["material"];
  layout: Record<keyof CompiledAsset["arrays"], { offset: number; byteLength: number }>;
}

export const sha256 = (buf: Uint8Array) => createHash("sha256").update(buf).digest("hex");

/** Packs attachment arrays into one 4-byte-aligned binary and copies their textures. */
export function writeAttachments(dataDir: string, file: string, assets: readonly CompiledAsset[]) {
  const chunks: Uint8Array[] = [];
  let size = 0;
  const entries: AttachmentEntry[] = [];
  for (const a of assets) {
    const layout = {} as AttachmentEntry["layout"];
    for (const [key, arr] of Object.entries(a.arrays) as [
      keyof CompiledAsset["arrays"],
      ArrayBufferView,
    ][]) {
      size = Math.ceil(size / 4) * 4;
      const bytes = new Uint8Array(arr.buffer, arr.byteOffset, arr.byteLength);
      layout[key] = { offset: size, byteLength: bytes.byteLength };
      chunks.push(bytes);
      size += bytes.byteLength;
    }
    entries.push({
      id: a.id,
      kind: a.kind,
      name: a.name,
      zDepth: a.zDepth,
      vertexCount: a.vertexCount,
      faceCount: a.faceCount,
      scale: a.scale,
      material: a.material,
      layout,
    });
    for (const [src, name] of a.textures) fs.copyFileSync(src, path.join(dataDir, name));
  }
  const bin = new Uint8Array(size);
  let o = 0;
  for (const c of chunks) {
    o = Math.ceil(o / 4) * 4;
    bin.set(c, o);
    o += c.byteLength;
  }
  fs.writeFileSync(path.join(dataDir, file), bin);
  return { entries, sha256: sha256(bin), byteLength: bin.byteLength };
}

/** Generates `index.js` and `index.d.ts` exporting `exportName` with a literal URL per data file. */
export function writePackEntry(packDir: string, exportName: string, description: string): void {
  const dataDir = path.join(packDir, "data");
  const files = fs
    .readdirSync(dataDir)
    .filter((f) => f !== "manifest.json" && f !== "PROVENANCE.md")
    .sort();
  const url = (f: string) => `new URL(${JSON.stringify(`./data/${f}`)}, import.meta.url).href`;
  const js = [
    "// Generated by scripts/pack-makehuman.ts; do not edit.",
    "/**",
    ` * ${description}`,
    " * Every file is a literal `new URL(..., import.meta.url)` so bundlers emit it automatically.",
    " */",
    `export const ${exportName} = {`,
    `\tmanifest: ${url("manifest.json")},`,
    "\tfiles: {",
    ...files.map((f) => `\t\t${JSON.stringify(f)}: ${url(f)},`),
    "\t},",
    "};",
    "",
  ].join("\n");
  const dts = [
    "// Generated by scripts/pack-makehuman.ts; do not edit.",
    `/** ${description} */`,
    `export declare const ${exportName}: {`,
    "\treadonly manifest: string;",
    `\treadonly files: Readonly<Record<${files.map((f) => JSON.stringify(f)).join(" | ")}, string>>;`,
    "};",
    "",
  ].join("\n");
  fs.writeFileSync(path.join(packDir, "index.js"), js);
  fs.writeFileSync(path.join(packDir, "index.d.ts"), dts);
}
