/**
 * Writes compiled attachments into a pack directory and generates the pack's
 * `index.js` / `index.d.ts`, which export one literal
 * `new URL("./data/<file>", import.meta.url)` per file so bundlers emit every
 * binary and texture without configuration.
 */
import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { gzipSync } from "node:zlib";
import sharp from "sharp";
import type { CompiledAsset } from "./compileAsset.ts";

export interface AttachmentEntry {
  id: string;
  kind: string;
  name: string;
  zDepth: number;
  vertexCount: number;
  faceCount: number;
  scale: CompiledAsset["scale"];
  material: CompiledAsset["material"];
  layout: Record<keyof CompiledAsset["arrays"], { offset: number; byteLength: number }>;
}

export const sha256 = (buf: Uint8Array) => createHash("sha256").update(buf).digest("hex");

/** Longest texture edge shipped. On-screen, an eye or a mouth never needs more. */
const TEXTURE_MAX = 1024;

/**
 * Encodes a texture for the web: WebP at quality 88 with lossless alpha (the
 * eye's cornea is cut by its alpha, which must not blur), at most
 * TEXTURE_MAX pixels on a side. Output is deterministic for a sharp version.
 */
async function writeTexture(src: string, dest: string): Promise<void> {
  await sharp(src)
    .resize({ width: TEXTURE_MAX, height: TEXTURE_MAX, fit: "inside", withoutEnlargement: true })
    .webp({ quality: 88, alphaQuality: 100, effort: 6 })
    .toFile(dest);
}

/** Packs attachment arrays into one 4-byte-aligned binary and writes their textures. */
export async function writeAttachments(
  dataDir: string,
  file: string,
  assets: readonly CompiledAsset[],
) {
  // Textures from an earlier pack (or an earlier format) never linger.
  for (const f of fs.readdirSync(dataDir))
    if (/\.(png|jpe?g|webp)$/i.test(f)) fs.rmSync(path.join(dataDir, f));
  const chunks: Uint8Array[] = [];
  let size = 0;
  const entries: AttachmentEntry[] = [];
  for (const a of assets) {
    const layout = {} as AttachmentEntry["layout"];
    for (const [key, arr] of Object.entries(a.arrays) as [
      keyof CompiledAsset["arrays"],
      ArrayBufferView,
    ][]) {
      size = Math.ceil(size / 4) * 4;
      const bytes = new Uint8Array(arr.buffer, arr.byteOffset, arr.byteLength);
      layout[key] = { offset: size, byteLength: bytes.byteLength };
      chunks.push(bytes);
      size += bytes.byteLength;
    }
    entries.push({
      id: a.id,
      kind: a.kind,
      name: a.name,
      zDepth: a.zDepth,
      vertexCount: a.vertexCount,
      faceCount: a.faceCount,
      scale: a.scale,
      material: a.material,
      layout,
    });
    for (const [src, name] of a.textures) await writeTexture(src, path.join(dataDir, name));
  }
  const bin = new Uint8Array(size);
  let o = 0;
  for (const c of chunks) {
    o = Math.ceil(o / 4) * 4;
    bin.set(c, o);
    o += c.byteLength;
  }
  // Gzipped for transfer, like every pack binary; offsets refer to the decoded file.
  const gz = new Uint8Array(gzipSync(bin, { level: 9 }));
  fs.writeFileSync(path.join(dataDir, file), gz);
  return { entries, sha256: sha256(gz), byteLength: bin.byteLength };
}

/** Generates `index.js` and `index.d.ts` exporting `exportName` with a literal URL per data file. */
export function writePackEntry(packDir: string, exportName: string, description: string): void {
  const dataDir = path.join(packDir, "data");
  const files = fs
    .readdirSync(dataDir)
    .filter((f) => f !== "manifest.json" && f !== "PROVENANCE.md")
    .sort();
  const url = (f: string) => `new URL(${JSON.stringify(`./data/${f}`)}, import.meta.url).href`;
  const js = [
    "// Generated by scripts/pack-makehuman.ts; do not edit.",
    "/**",
    ` * ${description}`,
    " * Every file is a literal `new URL(..., import.meta.url)` so bundlers emit it automatically.",
    " */",
    `export const ${exportName} = {`,
    `\tmanifest: ${url("manifest.json")},`,
    "\tfiles: {",
    ...files.map((f) => `\t\t${JSON.stringify(f)}: ${url(f)},`),
    "\t},",
    "};",
    "",
  ].join("\n");
  const dts = [
    "// Generated by scripts/pack-makehuman.ts; do not edit.",
    `/** ${description} */`,
    `export declare const ${exportName}: {`,
    "\treadonly manifest: string;",
    `\treadonly files: Readonly<Record<${files.map((f) => JSON.stringify(f)).join(" | ")}, string>>;`,
    "};",
    "",
  ].join("\n");
  fs.writeFileSync(path.join(packDir, "index.js"), js);
  fs.writeFileSync(path.join(packDir, "index.d.ts"), dts);
}
