// Generated by scripts/pack-makehuman.ts; do not edit.
/**
 * URLs of the humanoid-kit-body pack files. Pass to `loadHumanoidAssets({ body })`.
 * Every file is a literal `new URL(..., import.meta.url)` so bundlers emit it automatically.
 */
export const bodyPack = {
	manifest: new URL("./data/manifest.json", import.meta.url).href,
	files: {
		"attachments.bin.gz": new URL("./data/attachments.bin.gz", import.meta.url).href,
		"body.bin.gz": new URL("./data/body.bin.gz", import.meta.url).href,
		"eyes_high-poly_brown_eye.webp": new URL("./data/eyes_high-poly_brown_eye.webp", import.meta.url).href,
		"modifier-targets.bin.gz": new URL("./data/modifier-targets.bin.gz", import.meta.url).href,
		"targets.bin.gz": new URL("./data/targets.bin.gz", import.meta.url).href,
		"teeth_base_teeth.webp": new URL("./data/teeth_base_teeth.webp", import.meta.url).href,
		"tongue_base_tongue01_diffuse.webp": new URL("./data/tongue_base_tongue01_diffuse.webp", import.meta.url).href,
	},
};
