// Generated by scripts/pack-makehuman.ts; do not edit.
/** URLs of the humanoid-kit-body pack files. Pass to `loadHumanoidAssets({ body })`. */
export declare const bodyPack: {
	readonly manifest: string;
	readonly files: Readonly<Record<"attachments.bin" | "body.bin" | "eyes_high-poly_brown_eye.png" | "targets.bin" | "teeth_base_teeth.png" | "tongue_base_tongue01_diffuse.png", string>>;
};
