// Generated by scripts/pack-makehuman.ts; do not edit.
/**
 * URLs of the humanoid-kit-body pack files. Pass to `loadHumanoidAssets({ body })`.
 * Every file is a literal `new URL(..., import.meta.url)` so bundlers emit it automatically.
 */
export const bodyPack = {
	manifest: new URL("./data/manifest.json", import.meta.url).href,
	files: {
		"attachments.bin": new URL("./data/attachments.bin", import.meta.url).href,
		"body.bin": new URL("./data/body.bin", import.meta.url).href,
		"eyes_high-poly_brown_eye.png": new URL("./data/eyes_high-poly_brown_eye.png", import.meta.url).href,
		"targets.bin": new URL("./data/targets.bin", import.meta.url).href,
		"teeth_base_teeth.png": new URL("./data/teeth_base_teeth.png", import.meta.url).href,
		"tongue_base_tongue01_diffuse.png": new URL("./data/tongue_base_tongue01_diffuse.png", import.meta.url).href,
	},
};
