/**
 * Generates src/surface/scatterTable.ts: Penner's pre-integrated diffusion
 * (src/surface/preintegration.ts) tabulated for the skin shader.
 *
 *   node scripts/generate-scatter-table.ts
 *
 * Rows are u = x / (x + KNEE) from 0 (no scatter) to 1 (x = ∞), columns N·L
 * from −1 to 1, both at texel centres. Each entry is the residual
 * D(N·L, x) − max(N·L, 0): the shader adds the exact Lambert term back, so the
 * table never has to resolve Lambert's knee at the terminator. Values are
 * stored as IEEE half floats (three's encoder), base64, for a single-channel
 * half-float texture, which every WebGL 2 device filters linearly.
 * Deterministic: the same code always writes the same bytes, which
 * tests/scatter.test.ts checks.
 */
import fs from "node:fs";
import path from "node:path";
import { DataUtils } from "three";
import { preintegratedDiffuse } from "../src/surface/preintegration.ts";

/** Odd, so N·L = 0, where the residual has Lambert's kink, falls on a texel centre. */
export const COS_STEPS = 129;
export const U_STEPS = 64;
export const KNEE = 0.25;
/** Stands in for x = ∞ (the profile far wider than the sphere). */
const X_INFINITY = 1e4;

export function generateScatterTable(): Uint16Array {
  const out = new Uint16Array(COS_STEPS * U_STEPS);
  for (let j = 0; j < U_STEPS; j++) {
    const u = j / (U_STEPS - 1);
    const x = j === U_STEPS - 1 ? X_INFINITY : (KNEE * u) / (1 - u);
    for (let i = 0; i < COS_STEPS; i++) {
      const c = -1 + (2 * i) / (COS_STEPS - 1);
      out[j * COS_STEPS + i] = DataUtils.toHalfFloat(preintegratedDiffuse(c, x) - Math.max(c, 0));
    }
  }
  return out;
}

export function scatterTableSource(table: Uint16Array): string {
  const base64 = Buffer.from(table.buffer, table.byteOffset, table.byteLength).toString("base64");
  return [
    "// Generated by scripts/generate-scatter-table.ts; do not edit.",
    "/**",
    " * Penner's pre-integrated diffusion of Burley's profile, minus Lambert:",
    " * `uSteps` rows of u = x / (x + knee) from 0 to 1 (x = ∞), each `cosSteps`",
    " * columns of N·L from −1 to 1, as little-endian half floats in base64.",
    " */",
    "export const SCATTER_TABLE = {",
    `  cosSteps: ${COS_STEPS},`,
    `  uSteps: ${U_STEPS},`,
    `  knee: ${KNEE},`,
    `  data: "${base64}",`,
    "} as const;",
    "",
  ].join("\n");
}

if (import.meta.main) {
  const file = path.resolve(import.meta.dirname, "../src/surface/scatterTable.ts");
  fs.writeFileSync(file, scatterTableSource(generateScatterTable()));
  console.log(`wrote ${path.relative(process.cwd(), file)} (${COS_STEPS} × ${U_STEPS})`);
}
