// Generated by scripts/pack-makehuman.ts; do not edit.
/**
 * URLs of the humanoid-kit-adult-anatomy pack files. Pass to `loadHumanoidAssets({ adultAnatomy })`.
 * Every file is a literal `new URL(..., import.meta.url)` so bundlers emit it automatically.
 */
export const adultAnatomyPack = {
	manifest: new URL("./data/manifest.json", import.meta.url).href,
	files: {
		"targets.bin": new URL("./data/targets.bin", import.meta.url).href,
	},
};
